# Generated by Django 4.2.1 on 2024-03-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_loginiciosesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginiciosesion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='loginiciosesion',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
