# Generated by Django 4.2.1 on 2024-03-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_loginiciosesion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginiciosesion',
            name='texto',
            field=models.CharField(default='Inicio de sesión', max_length=100),
        ),
    ]
