# Generated by Django 4.2.1 on 2024-03-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_loginiciosesion_texto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogInicioSesion',
            new_name='Log',
        ),
    ]
