# Generated by Django 4.2.1 on 2024-03-19 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='duracion_conv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_duracion')),
                ('tipo_duracion', models.CharField(choices=[('0-15 min', '0-15 min'), ('15-30 min', '15-30 min'), ('30-60 min', '30-60 min'), ('Más de 60 min', 'Más de 60 min')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='frecuencia_conv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_frecuencia')),
                ('tipo_frecuencia', models.CharField(choices=[('Esporadica', 'Esporadica'), ('Mensual', 'Mensual'), ('Semanal', 'Semanal'), ('Diaria', 'Diaria'), ('Varias veces al día', 'Varias veces al día')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='funcion_conv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_duracion')),
                ('tipo_funcion', models.CharField(choices=[('Satisfacción de las necesidades vitales', 'Satisfacción de las necesidades vitales'), ('Emociones o propósito en la vida', 'Emociones o propósito en la vida'), ('Noticias o información mundial', 'Noticias o información mundial'), ('Otro', 'Otro')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='genero_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_genero')),
                ('nombre_genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtrasEnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_otras_enf', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='satisfaccion_conv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_duracion')),
                ('tipo_satisfaccion', models.CharField(choices=[('Nada satisfecho', 'Nada satisfecho'), ('Poco satisfecho', 'Poco satisfecho'), ('Medianamente satisfecho', 'Medianamente satisfecho'), ('Satisfecho', 'Satisfecho'), ('Muy satisfecho', 'Muy satisfecho')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sistema_salud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_sistema')),
                ('nombre_sistema', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_diagnostico_flgo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_etiqueta')),
                ('nombre_diagnostico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_relacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_relacion')),
                ('tipo_relacion', models.CharField(choices=[('Conyuge', 'Conyuge'), ('Hijo o Hija', 'Hijo o Hija'), ('Otros familiares', 'Otros familiares'), ('Otras personas', 'Otras personas')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='formulario_com',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_formulario')),
                ('id_fono', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('ano_nac', models.CharField(max_length=10, verbose_name='año Nacimiento')),
                ('complemento_1', models.CharField(blank=True, max_length=2000, null=True)),
                ('complemento_2', models.CharField(blank=True, max_length=2000, null=True)),
                ('complemento_3', models.CharField(blank=True, max_length=2000, null=True)),
                ('complemento_4', models.CharField(blank=True, max_length=2000, null=True)),
                ('duracion_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_1', to='botApp.duracion_conv', verbose_name='duracion_1')),
                ('duracion_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_2', to='botApp.duracion_conv', verbose_name='duracion_2')),
                ('duracion_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_3', to='botApp.duracion_conv', verbose_name='duracion_3')),
                ('duracion_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_4', to='botApp.duracion_conv', verbose_name='duracion_4')),
                ('frecuencia_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_1', to='botApp.frecuencia_conv', verbose_name='frecuencia_1')),
                ('frecuencia_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_2', to='botApp.frecuencia_conv', verbose_name='frecuencia_2')),
                ('frecuencia_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_3', to='botApp.frecuencia_conv', verbose_name='frecuencia_3')),
                ('frecuencia_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_4', to='botApp.frecuencia_conv', verbose_name='frecuencia_4')),
                ('funcion_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_1', to='botApp.funcion_conv', verbose_name='funcion_1')),
                ('funcion_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_2', to='botApp.funcion_conv', verbose_name='funcion_2')),
                ('funcion_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_3', to='botApp.funcion_conv', verbose_name='funcion_3')),
                ('funcion_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_4', to='botApp.funcion_conv', verbose_name='funcion_4')),
                ('genero_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.genero_usuario')),
                ('satisfaccion_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_1', to='botApp.satisfaccion_conv', verbose_name='satisfaccion_1')),
                ('satisfaccion_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_2', to='botApp.satisfaccion_conv', verbose_name='satisfaccion_2')),
                ('satisfaccion_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_3', to='botApp.satisfaccion_conv', verbose_name='satisfaccion_3')),
                ('satisfaccion_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_4', to='botApp.satisfaccion_conv', verbose_name='satisfaccion_4')),
                ('tipo_relacion_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_1', to='botApp.tipo_relacion', verbose_name='tipo_relacion_1')),
                ('tipo_relacion_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_2', to='botApp.tipo_relacion', verbose_name='tipo_relacion_2')),
                ('tipo_relacion_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_3', to='botApp.tipo_relacion', verbose_name='tipo_relacion_3')),
                ('tipo_relacion_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_4', to='botApp.tipo_relacion', verbose_name='tipo_relacion_4')),
            ],
        ),
        migrations.CreateModel(
            name='audio_persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_audio')),
                ('wsp_usuario', models.CharField(max_length=30)),
                ('ano_nac', models.CharField(max_length=10, verbose_name='año_nacimiento')),
                ('comuna_usuario', models.CharField(max_length=30, verbose_name='comuna')),
                ('audio_manychat', models.CharField(max_length=255)),
                ('fecha_registro_paciente', models.DateTimeField(default=django.utils.timezone.now)),
                ('audio_fisico', models.URLField(blank=True, null=True)),
                ('genero_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.genero_usuario')),
                ('sistema_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.sistema_salud')),
            ],
        ),
        migrations.CreateModel(
            name='audio_fono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_audio')),
                ('id_usuario', models.IntegerField()),
                ('nombre_paciente', models.CharField(max_length=20)),
                ('audio_fo1', models.FileField(upload_to='audios/fono/')),
                ('audio_fo2', models.FileField(blank=True, null=True, upload_to='audios/fono/')),
                ('audio_fo3', models.FileField(blank=True, null=True, upload_to='audios/fono/')),
                ('audio_fo4', models.FileField(blank=True, null=True, upload_to='audios/fono/')),
                ('audio_fo5', models.FileField(blank=True, null=True, upload_to='audios/fono/')),
                ('ano_nac', models.CharField(max_length=10, verbose_name='Año Nacimiento')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('genero_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.genero_usuario')),
                ('otras_enf', models.ManyToManyField(to='botApp.otrasenf')),
                ('tipo_diagnostico_flgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.tipo_diagnostico_flgo')),
            ],
        ),
    ]
