# Generated by Django 4.2.1 on 2024-02-06 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="audio_etiqueta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id_etiqueta"
                    ),
                ),
                (
                    "nombre_etiqueta",
                    models.CharField(
                        choices=[
                            ("Disartria", "Disartria"),
                            ("Disfagia", "Disfagia"),
                            ("Voz_Habla", "Voz_Habla"),
                            ("Otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="audio_fono",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id_audio"
                    ),
                ),
                ("audio_fo", models.FileField(upload_to="audios/")),
                (
                    "ano_nac",
                    models.CharField(max_length=10, verbose_name="año_nacimiento"),
                ),
                (
                    "fecha_ingreso_fono",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "audio_etiqueta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="botApp.audio_etiqueta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="audio_persona",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id_audio"
                    ),
                ),
                ("audio_us", models.FileField(upload_to="audios/")),
                ("wsp_usuario", models.IntegerField()),
                (
                    "ano_nac",
                    models.CharField(max_length=10, verbose_name="año_nacimiento"),
                ),
                (
                    "fecha_ingreso_persona",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "audio_etiqueta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="botApp.audio_etiqueta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="genero_usuario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id_genero"
                    ),
                ),
                (
                    "nombre_genero",
                    models.CharField(
                        choices=[
                            ("Femenino", "Femenino"),
                            ("Masculino", "Masculino"),
                            ("Otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id_usuario"
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=20)),
                ("apellido_usuario", models.CharField(max_length=20)),
                ("correo_usuario", models.EmailField(max_length=40)),
                ("tipo_usuario", models.CharField(max_length=20)),
                (
                    "audio_fono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="botApp.audio_fono",
                    ),
                ),
                (
                    "audio_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="botApp.audio_persona",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="audio_persona",
            name="genero_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="botApp.genero_usuario"
            ),
        ),
        migrations.AddField(
            model_name="audio_fono",
            name="genero_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="botApp.genero_usuario"
            ),
        ),
    ]
