# Generated by Django 4.2.1 on 2024-03-05 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genero_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_genero')),
                ('nombre_genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtrasEnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_otras_enf', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_diagnostico_flgo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_etiqueta')),
                ('nombre_diagnostico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_tipo_usuario')),
                ('nombre_tipo_usuario', models.CharField(choices=[('Usuario', 'Usuario'), ('Paciente', 'Paciente'), ('admin', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='audio_persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_audio')),
                ('wsp_usuario', models.CharField(max_length=30)),
                ('ano_nac', models.CharField(max_length=10, verbose_name='año_nacimiento')),
                ('comuna_residencia', models.CharField(max_length=30, verbose_name='comuna_residencia')),
                ('audio_manychat', models.CharField(max_length=255)),
                ('audio_fisico', models.FileField(blank=True, null=True, upload_to='audios/fono/')),
                ('fecha_registro_paciente', models.DateTimeField(default=django.utils.timezone.now)),
                ('genero_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.genero_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='audio_fono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_audio')),
                ('id_usuario', models.IntegerField()),
                ('nombre_paciente', models.CharField(max_length=20)),
                ('audio_fo1', models.FileField(upload_to='audios/fono/')),
                ('audio_fo2', models.FileField(blank=True, null=True, upload_to='audios/fono/')),
                ('audio_fo3', models.FileField(blank=True, null=True, upload_to='audios/fono/')),
                ('audio_fo4', models.FileField(blank=True, null=True, upload_to='audios/fono/')),
                ('audio_fo5', models.FileField(blank=True, null=True, upload_to='audios/fono/')),
                ('ano_nac', models.CharField(max_length=10, verbose_name='Año Nacimiento')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('genero_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.genero_usuario')),
                ('otras_enf', models.ManyToManyField(to='botApp.otrasenf')),
                ('tipo_diagnostico_flgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.tipo_diagnostico_flgo')),
            ],
        ),
    ]
