# Generated by Django 4.2.1 on 2024-03-21 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario_com',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='formulario_com',
            name='id_fono',
            field=models.CharField(max_length=100),
        ),
    ]
