# Generated by Django 4.2.1 on 2024-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sistema_salud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_sistema')),
                ('nombre_sistema', models.CharField(max_length=100)),
            ],
        ),
    ]
