# Generated by Django 4.2.1 on 2024-02-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0002_tipo_usuario_remove_audio_fono_fecha_ingreso_fono_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="botApp.tipo_usuario"
            ),
        ),
    ]
