# Generated by Django 4.2.1 on 2024-03-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0002_sistema_salud'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_persona',
            name='sistema_salud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='botApp.sistema_salud'),
            preserve_default=False,
        ),
    ]
