# Generated by Django 4.2.1 on 2024-03-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0002_formulario_com_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_fono',
            name='id_usuario',
            field=models.CharField(max_length=30),
        ),
    ]
