# Generated by Django 4.2.1 on 2024-03-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0003_audio_persona_sistema_salud'),
    ]

    operations = [
        migrations.CreateModel(
            name='comuna_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_comuna')),
                ('nombre_comuna', models.CharField(max_length=100)),
            ],
        ),
    ]
