# Generated by Django 4.2.1 on 2024-02-07 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0003_alter_usuario_tipo_usuario"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="usuario",
            new_name="usuarioBot",
        ),
    ]
