# Generated by Django 4.2.1 on 2024-03-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0004_registro_fono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_fono',
            name='telefono_fono',
            field=models.IntegerField(),
        ),
    ]
