# Generated by Django 4.2.1 on 2024-02-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0004_rename_usuario_usuariobot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariobot",
            name="audio_fono",
        ),
        migrations.RemoveField(
            model_name="usuariobot",
            name="audio_persona",
        ),
        migrations.AddField(
            model_name="usuariobot",
            name="contrasena_usuario",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
