# Generated by Django 4.2.1 on 2024-03-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0004_comuna_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_persona',
            name='comuna_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='botApp.comuna_usuario'),
            preserve_default=False,
        ),
    ]
