# Generated by Django 4.2.1 on 2024-03-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0005_audio_persona_comuna_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_persona',
            name='comuna_usuario',
        ),
        migrations.DeleteModel(
            name='comuna_usuario',
        ),
    ]
