# Generated by Django 4.2.1 on 2024-02-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0005_remove_usuariobot_audio_fono_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariobot",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="id_usuario"
            ),
        ),
    ]
