# Generated by Django 4.2.1 on 2024-03-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0006_remove_audio_persona_comuna_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_persona',
            name='comuna_residencia',
        ),
        migrations.AddField(
            model_name='audio_persona',
            name='comuna_usuario',
            field=models.CharField(default=1, max_length=30, verbose_name='comuna'),
            preserve_default=False,
        ),
    ]
