# Generated by Django 4.2.1 on 2024-02-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0006_alter_usuariobot_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariobot",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id_usuario"
            ),
        ),
    ]
