# Generated by Django 4.2.1 on 2024-02-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0007_alter_usuariobot_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio_fono",
            name="id_paciente_ingresado",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
