# Generated by Django 4.2.1 on 2024-03-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0007_remove_audio_persona_comuna_residencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_persona',
            name='audio_fisico',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de descarga de ManyChat'),
        ),
    ]
