# Generated by Django 4.2.1 on 2024-02-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0008_audio_fono_id_paciente_ingresado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio_fono",
            name="ano_nac",
            field=models.CharField(max_length=10, verbose_name="Año Nacimiento"),
        ),
        migrations.AlterField(
            model_name="audio_fono",
            name="id_paciente_ingresado",
            field=models.CharField(max_length=10, verbose_name="Id Paciente"),
        ),
    ]
