# Generated by Django 4.2.1 on 2024-03-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0009_alter_audio_persona_audio_fisico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_persona',
            name='audio_fisico',
            field=models.URLField(blank=True, null=True),
        ),
    ]
