# Generated by Django 4.2.1 on 2024-02-07 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0009_alter_audio_fono_ano_nac_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio_fono",
            name="id_paciente_ingresado",
        ),
        migrations.AlterField(
            model_name="audio_fono",
            name="fecha_registro",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="audio_persona",
            name="fecha_registro_paciente",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name="usuarioBot",
        ),
    ]
