# Generated by Django 4.2.1 on 2024-02-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0010_remove_audio_fono_id_paciente_ingresado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio_persona",
            name="id_fono",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
