# Generated by Django 4.2.1 on 2024-02-08 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0011_audio_persona_id_fono"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio_persona",
            name="id_fono",
        ),
    ]
