# Generated by Django 4.2.1 on 2024-03-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0012_alter_duracion_conv_tipo_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario_com',
            name='complementos',
        ),
        migrations.RemoveField(
            model_name='formulario_com',
            name='duracion_conv',
        ),
        migrations.RemoveField(
            model_name='formulario_com',
            name='frecuencia_conv',
        ),
        migrations.RemoveField(
            model_name='formulario_com',
            name='funcion_conv',
        ),
        migrations.RemoveField(
            model_name='formulario_com',
            name='satisfaccion_conv',
        ),
        migrations.RemoveField(
            model_name='formulario_com',
            name='tipo_relacion',
        ),
        migrations.CreateModel(
            name='respuestas_form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_respuestas')),
                ('complementos', models.CharField(max_length=1000)),
                ('duracion_conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.duracion_conv')),
                ('frecuencia_conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.frecuencia_conv')),
                ('funcion_conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.funcion_conv')),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.formulario_com')),
                ('satisfaccion_conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.satisfaccion_conv')),
                ('tipo_relacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.tipo_relacion')),
            ],
        ),
    ]
