# Generated by Django 4.2.1 on 2024-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0012_remove_audio_persona_id_fono"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio_fono",
            name="id_fono",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
