# Generated by Django 4.2.1 on 2024-03-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0013_remove_formulario_com_complementos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas_form',
            name='complementos',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='respuestas_form',
            name='duracion_conv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.duracion_conv'),
        ),
        migrations.AlterField(
            model_name='respuestas_form',
            name='frecuencia_conv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.frecuencia_conv'),
        ),
        migrations.AlterField(
            model_name='respuestas_form',
            name='funcion_conv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.funcion_conv'),
        ),
        migrations.AlterField(
            model_name='respuestas_form',
            name='id_formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.formulario_com'),
        ),
        migrations.AlterField(
            model_name='respuestas_form',
            name='satisfaccion_conv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.satisfaccion_conv'),
        ),
        migrations.AlterField(
            model_name='respuestas_form',
            name='tipo_relacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.tipo_relacion'),
        ),
    ]
