# Generated by Django 4.2.1 on 2024-02-09 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("botApp", "0013_audio_fono_id_fono"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audio_fono",
            old_name="id_fono",
            new_name="id_usuario",
        ),
    ]
