# Generated by Django 4.2.1 on 2024-02-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0014_rename_id_fono_audio_fono_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_fono',
            name='nombre_paciente',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
