# Generated by Django 4.2.1 on 2024-03-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0014_alter_respuestas_form_complementos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario_com',
            name='complemento_1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='complemento_2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='complemento_3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='complemento_4',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='duracion_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_1', to='botApp.duracion_conv', verbose_name='duracion_1'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='duracion_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_2', to='botApp.duracion_conv', verbose_name='duracion_2'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='duracion_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_3', to='botApp.duracion_conv', verbose_name='duracion_3'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='duracion_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_4', to='botApp.duracion_conv', verbose_name='duracion_4'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='frecuencia_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_1', to='botApp.frecuencia_conv', verbose_name='frecuencia_1'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='frecuencia_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_2', to='botApp.frecuencia_conv', verbose_name='frecuencia_2'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='frecuencia_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_3', to='botApp.frecuencia_conv', verbose_name='frecuencia_3'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='frecuencia_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_4', to='botApp.frecuencia_conv', verbose_name='frecuencia_4'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='funcion_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_1', to='botApp.funcion_conv', verbose_name='funcion_1'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='funcion_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_2', to='botApp.funcion_conv', verbose_name='funcion_2'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='funcion_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_3', to='botApp.funcion_conv', verbose_name='funcion_3'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='funcion_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_4', to='botApp.funcion_conv', verbose_name='funcion_4'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='satisfaccion_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_1', to='botApp.satisfaccion_conv', verbose_name='satisfaccion_1'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='satisfaccion_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_2', to='botApp.satisfaccion_conv', verbose_name='satisfaccion_2'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='satisfaccion_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_3', to='botApp.satisfaccion_conv', verbose_name='satisfaccion_3'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='satisfaccion_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_4', to='botApp.satisfaccion_conv', verbose_name='satisfaccion_4'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='tipo_relacion_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_1', to='botApp.tipo_relacion', verbose_name='tipo_relacion_1'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='tipo_relacion_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_2', to='botApp.tipo_relacion', verbose_name='tipo_relacion_2'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='tipo_relacion_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_3', to='botApp.tipo_relacion', verbose_name='tipo_relacion_3'),
        ),
        migrations.AddField(
            model_name='formulario_com',
            name='tipo_relacion_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_com_4', to='botApp.tipo_relacion', verbose_name='tipo_relacion_4'),
        ),
        migrations.AlterField(
            model_name='formulario_com',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='respuestas_form',
        ),
    ]
