# Generated by Django 4.2.1 on 2024-02-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0015_audio_fono_nombre_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_etiqueta',
            name='nombre_etiqueta',
            field=models.CharField(choices=[('Disartria', 'Disartria'), ('Disfagia', 'Disfagia'), ('Voz_Habla', 'Voz_Habla'), ('Paciente_Sano', 'Paciente_Sano'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
