# Generated by Django 4.2.1 on 2024-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0015_formulario_com_complemento_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario_com',
            name='id_fono',
            field=models.CharField(default=1, max_length=5, verbose_name='id_fono'),
            preserve_default=False,
        ),
    ]
