# Generated by Django 4.2.1 on 2024-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0016_formulario_com_id_fono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_com',
            name='id_fono',
            field=models.IntegerField(),
        ),
    ]
