# Generated by Django 4.2.1 on 2024-02-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0017_audio_fono_otras_enfermedades'),
    ]

    operations = [
        migrations.CreateModel(
            name='enfermedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_enfermedad')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='audio_fono',
            name='otras_enfermedades',
        ),
        migrations.AddField(
            model_name='audio_fono',
            name='otras_enfermedades',
            field=models.ManyToManyField(blank=True, to='botApp.enfermedad', verbose_name='Otras enfermedades'),
        ),
    ]
