# Generated by Django 4.2.1 on 2024-02-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0018_enfermedad_remove_audio_fono_otras_enfermedades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_fono',
            name='audio_fo2',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='audio_fono',
            name='audio_fo3',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='audio_fono',
            name='audio_fo4',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='audio_fono',
            name='audio_fo5',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
