# Generated by Django 4.2.1 on 2024-02-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0019_audio_fono_audio_fo2_audio_fono_audio_fo3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_fono',
            name='otras_enfermedades',
        ),
        migrations.DeleteModel(
            name='enfermedad',
        ),
    ]
