# Generated by Django 4.2.1 on 2024-02-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0020_remove_audio_fono_otras_enfermedades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_fono',
            name='otras_enfermedades',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
