# Generated by Django 4.2.1 on 2024-02-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0022_rename_audio_etiqueta_tipo_diagnostico_flgo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_diagnostico_flgo',
            name='nombre_etiqueta',
        ),
        migrations.AddField(
            model_name='tipo_diagnostico_flgo',
            name='nombre_diagnostico',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
