# Generated by Django 4.2.1 on 2024-02-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0023_remove_tipo_diagnostico_flgo_nombre_etiqueta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio_fono',
            old_name='audio_fo',
            new_name='audio_fo1',
        ),
    ]
