# Generated by Django 4.2.1 on 2024-02-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0024_rename_audio_fo_audio_fono_audio_fo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_persona',
            name='comuna_residencia',
            field=models.CharField(default=1, max_length=10, verbose_name='comuna_residencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio_persona',
            name='sistema_salud',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
