# Generated by Django 4.2.1 on 2024-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0027_remove_audio_persona_tipo_diagnostico_flgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_persona',
            name='audio_us',
            field=models.FileField(upload_to='audios/'),
        ),
    ]
