# Generated by Django 4.2.1 on 2024-02-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0028_alter_audio_persona_audio_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_fono',
            name='audio_fo1',
            field=models.FileField(upload_to='audios/fono/'),
        ),
        migrations.AlterField(
            model_name='audio_fono',
            name='audio_fo2',
            field=models.FileField(blank=True, null=True, upload_to='audios/fono/'),
        ),
        migrations.AlterField(
            model_name='audio_fono',
            name='audio_fo3',
            field=models.FileField(blank=True, null=True, upload_to='audios/fono/'),
        ),
        migrations.AlterField(
            model_name='audio_fono',
            name='audio_fo4',
            field=models.FileField(blank=True, null=True, upload_to='audios/fono/'),
        ),
        migrations.AlterField(
            model_name='audio_fono',
            name='audio_fo5',
            field=models.FileField(blank=True, null=True, upload_to='audios/fono/'),
        ),
        migrations.AlterField(
            model_name='audio_persona',
            name='audio_us',
            field=models.FileField(upload_to='audios/persona/'),
        ),
    ]
