# Generated by Django 4.2.1 on 2024-02-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0029_alter_audio_fono_audio_fo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_persona',
            name='audio_us',
        ),
        migrations.AddField(
            model_name='audio_persona',
            name='audio_usuario',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio_persona',
            name='comuna_residencia',
            field=models.CharField(max_length=30, verbose_name='comuna_residencia'),
        ),
    ]
