# Generated by Django 4.2.1 on 2024-02-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0030_remove_audio_persona_audio_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_persona',
            name='wsp_usuario',
            field=models.CharField(max_length=30),
        ),
    ]
