# Generated by Django 4.2.1 on 2024-02-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0032_rename_audio_usuario_audio_persona_audio_manychat'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_persona',
            name='audio_fisico',
            field=models.FileField(blank=True, null=True, upload_to='audios/fono/'),
        ),
    ]
