# Generated by Django 4.2.1 on 2024-02-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0035_otras_enf'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtrasEnf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_otras_enf', models.CharField(choices=[('Enfermedad de Parkinson', 'Enfermedad de Parkinson'), ('Diabetes', 'Diabetes'), ('Hipertensión', 'Hipertensión'), ('Ninguna', 'Ninguna')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='otras_enf',
        ),
        migrations.AddField(
            model_name='audio_fono',
            name='otras_enf',
            field=models.ManyToManyField(to='botApp.otrasenf'),
        ),
    ]
