# Generated by Django 4.2.1 on 2024-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0036_otrasenf_delete_otras_enf_audio_fono_otras_enf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero_usuario',
            name='nombre_genero',
            field=models.CharField(max_length=20),
        ),
    ]
