# Generated by Django 4.2.1 on 2024-03-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0039_alter_genero_usuario_nombre_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sistemaSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_sistema')),
                ('nombre_sistema', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='audio_persona',
            name='sistema_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.sistemasalud'),
        ),
    ]
