# Generated by Django 4.2.1 on 2024-03-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0040_sistemasalud_alter_audio_persona_sistema_salud'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sistemaSalud',
            new_name='sistema_salud',
        ),
    ]
