# Generated by Django 4.2.1 on 2024-03-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0041_rename_sistemasalud_sistema_salud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_persona',
            name='sistema_salud',
        ),
        migrations.DeleteModel(
            name='sistema_salud',
        ),
    ]
